version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - network_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=network_db
  minio:
    image: minio/minio
    ports: 
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ACESS_KEY=root
      - MINIO_SECRET_KEY=root
  backend:
    image: node:14
    command: npm run tnode
    ports:
      - 3000:3000
    volumes:
      - .:/srv/backend:rw
    working_dir: /srv/backend
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - backend
   

volumes:
  network_db_data: ~