version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./network_backend/network_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=network_db
  minio:
    image: minio/minio
    ports: 
      - "9000:9000"
    volumes:
      - ./network_backend/minio_data:/data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: password
    command: server /data
    depends_on: 
      - backend
  backend:
    image: node:14
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./network_backend:/srv/backend:rw
    working_dir: /srv/backend
    depends_on:
      - postgres
  frontend:
    image: node:14
    command: npm run serve
    ports:
      - 8080:8080
    volumes:
      - ./network_frontend:/srv/frontend:rw
    working_dir: /srv/frontend
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./network_backend/nginx:/etc/nginx/conf.d
    depends_on: 
      - backend
      - minio
      - frontend
   

volumes:
  network_db_data: ~