/**
 * UNIVSERSITY DATA - USED FOR THE SELECTION IN PROFILE
 */

//Faculties - Hochschule Hannover
export const faculties = [
  { id: 1, name: '‎‏‏‎ ‎' },
  { id: 2, name: 'Fakultät 1 - Elektro- und Informationstechnik' },
  { id: 3, name: 'Fakultät 2 - Maschinenbau und Bioverfahrenstechnik' },
  { id: 4, name: 'Fakultät 3 - Medien, Information und Design' },
  { id: 5, name: 'Fakultät 4 - Wirtschaft und Informatik' },
  { id: 6, name: 'Fakultät 5 - Diakonie, Gesundheit und Soziales' },
];

//Courses - Hochschule Hannover
export const courses = [
  { id: 1, name: '‏‏‎ ‎‎' },
  { id: 1, name: 'Angewandte Informatik (BIN)' },
  { id: 2, name: 'Angewandte Informatik (MIN)' },
  { id: 3, name: 'Angewandte Mathematik (MAT)' },
  { id: 4, name: 'Bank- und Versicherungswesen (BBI)' },
  { id: 5, name: 'Betriebswirtschaftslehre (BBA)' },
  { id: 5, name: 'Bildungswissenschaften für Pflege- und Gesundheitsberufe (MBG)' },
  { id: 5, name: 'Design und Medien (MDM)' },
  { id: 5, name: 'Digitale Transformation (MDT)' },
  { id: 5, name: 'Elektrische Energiesysteme und Elektromobilität (EEE)' },
  { id: 5, name: 'Elektrotechnik und Informationstechnik (EIT)' },
  { id: 5, name: 'Fernsehjournalismus (MTV)' },
  { id: 5, name: 'Fotojournalismus und Dokumentarfotografie (BFO)' },
  { id: 5, name: 'Heilpädagogik - Inklusive Bildung und Begleitung - berufsintegrierend (HBI)' },
  { id: 5, name: 'Heilpädagogik - Inklusive Bildung und Begleitung (BAH)' },
  { id: 5, name: 'Informationsmanagement (BIM)' },
  { id: 5, name: 'Informationsmanagement berufsbegleitend (BIB)' },
  { id: 5, name: 'Ingenieurinformatik Maschinenbau (IIM)' },
  { id: 5, name: 'Innenarchitektur (BIA)' },
  { id: 5, name: 'Integrated Media & Communication (IMC) Dual' },
  { id: 5, name: 'International Business Studies (IBS)' },
  { id: 5, name: 'Journalistik (BJO)' },
  { id: 5, name: 'Kommunikationsmanagement (MKO)' },
  { id: 5, name: 'Konstruktionstechnik dual (KTD)' },
  { id: 5, name: 'Sensor- und Automatisierungstechnik (ESA)' },
  { id: 5, name: 'Social Work - berufsbegleitend (MSW)' },
  { id: 5, name: 'Soziale Arbeit - berufsbegleitend (SBW)' },
  { id: 5, name: 'Soziale Arbeit - grundständig (BSW)' },
  { id: 5, name: 'Szenografie – Kostüm – Experimentelle Gestaltung (SKE)' },
  { id: 5, name: 'Technisches Informationsdesign und Technische Redaktion (ITR)' },
  { id: 5, name: 'Technologie Nachwachsender Rohstoffe (TNR)' },
  { id: 5, name: 'Unternehmensentwicklung (MBD)' },
  { id: 5, name: 'Veranstaltungsmanagement (BVM)' },
  { id: 5, name: 'Verfahrenstechnik, Energietechnik und Umwelttechnik (VEU)' },
  { id: 5, name: 'Verwaltungsinformatik (VIF)' },
  { id: 5, name: 'Visuelle Kommunikation (BVK)' },
  { id: 5, name: 'Wertschöfungsmanagement im Maschinenbau dual (WMM)' },
  { id: 5, name: 'Wirtschaftsinformatik (BIS)' },
  { id: 5, name: 'Wirtschaftsingenieur Elektrotechnik (EWI)' },
  { id: 5, name: 'Wirtschaftsingenieur/in (Technischer Vertrieb) dual (WTD)' },
  { id: 5, name: 'Wirtschaftsingenieur/in Maschinenbau (WIM)' },
  { id: 5, name: 'Lebensmittelverpackungstechnologie (LMV)' },
  { id: 5, name: 'Management für Pflege- und Gesundheitsberufe (MMG)' },
  { id: 5, name: 'Maschinenbau (MAB)' },
  { id: 5, name: 'Maschinenbau-Entwicklung (MED)' },
  { id: 5, name: 'Mechatronik (MEC)' },
  { id: 5, name: 'Mechatronik dual (MTD)' },
  { id: 5, name: 'Mediendesign (BME)' },
  { id: 5, name: 'Mediendesigninformatik (MDI)' },
  { id: 5, name: 'Medizinisches Informationsmanagement (BMI)' },
  { id: 5, name: 'Medizinisches Informationsmanagement (MMI)' },
  { id: 5, name: 'Milch- und Verpackungswirtschaft (MMV)' },
  { id: 5, name: 'Milchwirtschaftliche Lebensmitteltechnologie (BML)' },
  { id: 5, name: 'Mittelständische Unternehmensführung in Entrepreneurship (MMU)' },
  { id: 5, name: 'Modedesign (BMO)' },
  { id: 5, name: 'Nachhaltiges Energie-Design (NED)' },
  { id: 5, name: 'Pflege (BDP)' },
  { id: 5, name: 'Produktdesign (BPD)' },
  { id: 5, name: 'Produktionstechnik dual (PTD)' },
  { id: 5, name: 'Prozess Engineering und Produktionsmanagement (PEP)' },
  { id: 5, name: 'Prozessmanagement Usability Engineering Industrie 4.0 (PUE)' },
  { id: 5, name: 'Public Relations (BPR)' },
  { id: 5, name: 'Religionspädagogik und Soziale Arbeit (BRS)' },
];
